# Generated by Django 2.2.16 on 2022-10-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_users',
        ),
    ]
